# Generated by Django 3.2.19 on 2026-01-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('duration', models.IntegerField()),
                ('release_date', models.DateField()),
                ('trailer_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
