# Generated by Django 3.2.19 on 2026-01-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Drama', 'Drama'), ('Comedy', 'Comedy')], max_length=20)),
                ('language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Telugu', 'Telugu')], max_length=20)),
            ],
        ),
    ]
